#ENC[AES256_GCM,data:v/2N4+B1Oz+gCF0o/SKEjntGqhFmjQxD00+WMhijf0fVrhg9e/o=,iv:l3h4OmGr+UB3VuOoKpSNxC9RwMl6Q06hjpSlooGdwZ8=,tag:vhFZ66Et2gnJgcq2V5ghDA==,type:comment]
example-key: ENC[AES256_GCM,data:L7MGbrQd5viiYABd6A==,iv:R+Tm2Kf7Pdna7/OlL488HkVqJuGgqytJXe4UBlOCYPs=,tag:Pw25zBJCMk2xk/lqlOv26g==,type:str]
#ENC[AES256_GCM,data:gNLDI0fmu2RaQLLCU/9Sx/ox2eoOiODeFfJyjfyCQfQ3KAiyxLlW4Ia0xFaszq1J7sb/oTwv6DM=,iv:zUmd/wpH8Aw1oT3FZJevdmQ/HFfd2D1hLiw/joXq97Y=,tag:frORrkPxOr4IWhhBO/oTcA==,type:comment]
#ENC[AES256_GCM,data:qglKOM4RVeER2IsLC4o+TjAInjD/7IdCw3S/KuJlybtJofkej5mM7a5zeuHg+xq10kiJRkOflcFAsQ2ecQFRy1kdFV+5YOq8,iv:9kg/YZrsONs8BfGmGK5g9Yo+/3fHCytYvOuD53Zc9ug=,tag:V/6ae2KniLE8U4Y5wib+ow==,type:comment]
myservice:
    my_subdir:
        my_secret: ENC[AES256_GCM,data:/J186VpG/6Sd,iv:L2U4OmLy/XXVYdOhDc4hS9jzUr8Icnr1n5GyPv3xnfo=,tag:FBU2O8o6sQnz16ni9j95Lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gxkkvep23tavr8xwgrkz6gqsu6adnr5wu8s3m5f77v588l2cnq6qy36w9t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQmw5c2lZU0hoTDIyOGUy
            SjVmMU84NnltWUtCdHF4VFNOblVidndHdHc0ClRxcDNLanhKWnI3QVQrTy9KbnJH
            WWpOUnlKNnNtQm1Xak8vWllQRU5nUkUKLS0tIGlET1NMamNPelVKeWNZYm5KMCtO
            cW0xRkhweUtjaWxuNVJhb2VCcnNXaU0KGYNfGpWzpyHm7yrKft28l6UGImKq1iLV
            1PPyp6MZTHuiBG5ASr9AZkpaM0/NH6Ri5V+O8YDkR+79jiknpRZpeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-28T15:33:46Z"
    mac: ENC[AES256_GCM,data:tlwO5aCT57X4XGGkMK69A7Nwr+unX92eS98jsLA+wwf4VC/QbJThrkrM65G4V+Q9z7/G1/mYObXfbRFPagludkflfzUcNho16CFCMG70Y7YghRUcWxZmfIlZNqmS+67BEg6vIFlkSqctwiKXe3qsm/+kCG4lheXN+KgGNGfAVUg=,iv:JJoqWc5KGAaW9tuylJmbGosbYnKx1pRNVvEjp8VD/dc=,tag:xvL8EPO/f15JGjREIJZ59g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
